coinbase_adapter:
    subscribe: /api/coinbase/wsFeed/subscribe
    auth: /api/auth
    host: localhost
    port: 9000
    subscribe_body:
        type: Subscribe
        productIds: []
        channels:
            - ticker

rethinkdb:
    host: localhost
    port: 28015
    db_name: cryptobot
